import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import {useAuth} from "../hooks/auth";
import {ReactNode} from "react";

interface layoutProps {
    title: string,
    children: ReactNode
}

export default function Layout({title, children}: layoutProps) {

    const { profile } = useAuth();

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header profile={!profile?.message ? profile : null} />
            {children}
            {profile?.message ? <Footer /> : null}
        </>
    )
}
