import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import {useAuth} from "../hooks/auth";
import {ReactNode} from "react";
import styles from '@/styles/Layout.module.css'

interface layoutProps {
    title: string,
    children: ReactNode
}

export default function Layout({title, children}: layoutProps) {

    const { user } = useAuth({ middleware: 'auth' });

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header user={!user?.message ? user : null} />
            <main className={styles.main}>
                {children}
            </main>

            {user?.message ? <Footer /> : null}
        </>
    )
}
